# -*- coding: utf-8 -*-
"""group-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6lMCoWlS2QPOnYHEh0EPHH30pghaPuG
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/laptop_price.csv", encoding='latin1')
data

data.info()

data.isnull().sum()

data.describe()

# Count '?' values in each column
question_mark_counts = (data == '?').sum()

# Display the counts
print(question_mark_counts)

"""Q.2 Correlation matrix between independent variables and dependent vairables"""

sp_data = data[['Inches','Ram','Weight','Price_euros']]
sp_data

sp_data['Ram'] = data['Ram'].str.replace('GB', '').astype(int)
sp_data['Weight'] = data['Weight'].str.replace('kg', '').astype(float)

sp_data

#correlation matrix
correlation_matrix = sp_data.corr()  #creating a correlation matrix
correlation_matrix

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
sns.heatmap(sp_data.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title("Correlation Matrix Heatmap")
plt.show()

data.columns

data

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

X = sp_data['Inches'].values.reshape(-1, 1)
y = sp_data['Price_euros']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

from sklearn.linear_model import LinearRegression
import numpy as np

lr = LinearRegression()

X_train = X_train
X_test = X_test

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

c = lr.intercept_
print("The y-intercept of trained data: ",c)

m = lr.coef_
print("The slope of trained data: ",m)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("The Mean Squared Error: ", mse)
print("Mean Absolute Error: ", mae)

r2 = r2_score(y_test, y_pred)
print("The R-squared (R2) Score:", r2)

import matplotlib.pyplot as plt

# Assuming X_test, y_test, and y_pred are your test features, actual prices, and predicted prices respectively

plt.figure(figsize=(10, 6))

# Scatter plot for actual prices
plt.scatter(X_test, y_test, color='yellow', label='Actual Prices')

# Line plot for predicted prices
plt.plot(X_test, y_pred, color='red', label='Predicted Prices')

plt.xlabel('Screen Size (Inches)')
plt.ylabel('Price (Euros)')
plt.title('Linear Regression: Actual vs Predicted Prices')
plt.legend()
plt.grid(True)  # Adding grid for better visualization
plt.show()

# Reshape X_train and X_test before splitting
X = sp_data['Ram'].values.reshape(-1, 1)
y = sp_data['Price_euros']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

# Create and train the linear regression model
lr = LinearRegression()
lr.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = lr.predict(X_test)

import matplotlib.pyplot as plt

# Assuming X_test, y_test, and y_pred are your test features, actual prices, and predicted prices respectively

plt.figure(figsize=(10, 6))

# Scatter plot for actual prices
plt.scatter(X_test, y_test, color='yellow', label='Actual Prices')

# Line plot for predicted prices
plt.plot(X_test, y_pred, color='red', label='Predicted Prices')

plt.xlabel('Ram size')
plt.ylabel('Predicted Price (euros)')
plt.title('Actual vs Predicted Prices')
plt.legend()
plt.grid(True)  # Adding grid for better visualization
plt.show()

# Calculate evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Print the evaluation metrics
print("Mean Squared Error: ", mse)
print("Mean Absolute Error: ", mae)
print("R-squared (R2) Score:", r2)

# Reshape X_train and X_test before splitting
X = sp_data['Weight'].values.reshape(-1, 1)
y = sp_data['Price_euros']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)

# Create and train the linear regression model
lr = LinearRegression()
lr.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = lr.predict(X_test)

import matplotlib.pyplot as plt

# Assuming X_test, y_test, and y_pred are your test features, actual prices, and predicted prices respectively

plt.figure(figsize=(10, 6))

# Scatter plot for actual prices
plt.scatter(X_test, y_test, color='yellow', label='Actual Prices')

# Line plot for predicted prices
plt.plot(X_test, y_pred, color='red', label='Predicted Prices')

plt.xlabel('Weight')
plt.ylabel('Predicted Price (euros)')
plt.title('Actual vs Predicted Prices')
plt.legend()
plt.grid(True)  # Adding grid for better visualization
plt.show()

# Calculating evaluation metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

# Printing the evaluation metrics
print("Mean Squared Error: ", mse)
print("Mean Absolute Error: ", mae)
print("R-squared (R2) Score:", r2)